# Unit test

jobs:
- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux']
    tf_versions: ['1.12']
    onnx_opsets: ['7']
    onnx_backends: {onnxruntime: ['0.1.3']}
    job:
      steps:
      - template: 'unit_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows', 'mac']
    tf_versions: ['1.12']
    onnx_opsets: ['7']
    onnx_backends: {onnxruntime: ['0.1.4']}
    job:
      steps:
      - template: 'unit_test.yml'
