# Unit test

jobs:
#- template: 'templates/job_generator.yml'
#  parameters:
#    platforms: ['linux', 'windows', 'mac']
#    tf_versions: ['1.11']
#    onnx_opsets: ['7']
#    onnx_backends: {onnxruntime: ['0.1.4']}
#    job:
#      steps:
#      - template: 'unit_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['linux', 'windows', 'mac']
    tf_versions: ['1.11']
    onnx_opsets: ['7']
    onnx_backends: {onnxruntime: ['0.1.4', '0.1.3']}
    job:
      steps:
      - bash: |
          cd examples
          export TF2ONNX_TEST_BACKEND=$(CI_ONNX_BACKEND)
          export TF2ONNX_TEST_OPSET=$(CI_ONNX_OPSET)
          export PYTHONUNBUFFERED=1
          python test.py
        timeoutInMinutes: 5
        displayName: 'Run test.py'
