# Unit test

jobs:
#- template: 'templates/job_generator.yml'
#  parameters:
#    platforms: ['linux']
#    tf_versions: ['1.12']
#    onnx_opsets: ['7']
#    onnx_backends: {onnxruntime: ['0.1.3']}
#    job:
#      steps:
#      - template: 'unit_test.yml'

#- template: 'templates/job_generator.yml'
#  parameters:
#    platforms: ['linux', 'windows', 'mac']
#    tf_versions: ['1.12']
#    onnx_opsets: ['7']
#    onnx_backends: {onnxruntime: ['0.1.4']}
#    job:
#      steps:
#      - template: 'unit_test.yml'

- template: 'templates/job_generator.yml'
  parameters:
    platforms: ['windows']
    python_versions: ['3.5']
    tf_versions: ['1.12']
    onnx_opsets: ['7']
    onnx_backends: {onnxruntime: ['0.1.4']}
    job:
      steps:
      - bash: pip install onnxruntime-0.1.4-cp35-cp35m-win_amd64.whl --ignore-installed
      - template: 'unit_test.yml'